### PR TITLE
fix(videojs-video-element): avoid AbortError when play() is called after ended

### LINKED ISSUE #184: <videojs-video> breaks when play() is called directly after ended event
When `play()` is called directly in the `ended` handler or very shortly after, the video is not rewound and played again.

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Videojs-Video-Element</title>
<script type="module" src="https://cdn.jsdelivr.net/npm/videojs-video-element@1.0/+esm"></script>
</head>
<body>
  <videojs-video id="video" controls width="320" height="240">
    <source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4" />
  </videojs-video>

  <script>
    const player = document.getElementById('video');

    player.addEventListener('ended', () => {
      player.play();
    });
  </script>
</body>
</html>
```

Error message in console:

> Uncaught (in promise) DOMException: The fetching process for the media resource was aborted by the user agent at the user's request. 

It does not seem to happen when `play` is called e.g. via an interval handler after 1000ms.

### PR DESCRIPTION
**Pull request by R-Delfino95**
## Summary
- Fixes #184: `player.play()` called inside the `ended` event handler rejects with `AbortError: The play() request was interrupted by a call to pause()`.
- The issue is a race inside video.js's own `play()` path when the player is in the `ended` state. Its internal reset/seek aborts the underlying play promise.
- Intercepted in `call()`: when `api.ended()` is true, seek to `0` via the video.js API, wait for the `seeked` event, then call `api.play()`. The new logic lives in a private `#rewindAndPlay()` method.

---

> [!NOTE]
> **Medium Risk**
> Changes `play()` behavior in `videojs-video-element` by adding a seek-and-retry path when the player is `ended`, which could affect edge-case playback flows and introduces a timed rejection if seeking stalls.
> 
> **Overview**
> Avoids `AbortError` when `play()` is invoked while video.js reports `ended` by intercepting calls in `call()` and performing a rewind-then-play sequence.
> 
> Adds a private `#rewindAndPlay()` helper that seeks to `0`, waits for the `seeked` event, then calls `api.play()` (with a 3s timeout that rejects with `AbortError` if the seek never completes).
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 12a1ac9f8913e63815d9efd42c504eb9307efa0f. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

File: packages/videojs-video-element/videojs-video-element.js [hunk 1]
```diff
@@ -222,9 +222,25 @@ class VideojsVideoElement extends (MediaTracksMixin?.(SuperVideoElement ?? class
...
+    return new Promise((resolve, reject) => {
+      this.api.one('seeked', () => {
+        const result = this.api.play();
+        if (result?.then) result.then(resolve, reject);
+        else resolve(result);
+      });
+      this.api.currentTime(0);
+    });
+  }
+
```
Comment (ronald-urbina) [inline packages/videojs-video-element/videojs-video-element.js]:
```suggestion
  #rewindAndPlay() {
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => {
        reject(new DOMException('Seek timed out', 'AbortError'));
      }, 3000);

      this.api.one('seeked', () => {
        clearTimeout(timeout);
        const result = this.api.play();
        if (result?.then) result.then(resolve, reject);
        else resolve(result);
      });
      this.api.currentTime(0);
    });
  }
```

**Review by ronald-urbina — CHANGES_REQUESTED** [review]

**Review by ronald-urbina — APPROVED** [review]
