### PR TITLE
fix: correct url generation for vimeo events

### LINKED ISSUE #181: [Vimeo] Cannot embed a Vimeo Event (livestream)
Hey, I'm using `react-player` which is using `<vimeo-video>` element under the hood. Recently I've encountered an issue with embedding a Vimeo Event. It seems that there is a problem with parsing the Vimeo URLs.

Currently all Vimeo URLs are transformed to a `https://player.vimeo.com/video/XXX` format which is incorrect for Vimeo Events. Depending on some settings it seems that the URL should be either `https://vimeo.com/event/XXX/embed` or `https://vimeo.com/event/XXX/embed/YYY`. 

Here is the minimal reproduction of this issue: 
https://codesandbox.io/p/sandbox/vimeo-video-element-forked-2tf69h
The URL `https://vimeo.com/event/5315267/embed` got resolved to `https://player.vimeo.com/video/5315267?preload=metadata&transparent=0&h=embed`.
Image

The issue seems to be in the `serializeIframeUrl` function which always returns the same base path.
https://github.com/muxinc/media-elements/blob/0b59b786c0b7064fcee660aa17e373e08f9931d9/packages/vimeo-video-element/vimeo-video-element.js#L3
https://github.com/muxinc/media-elements/blob/0b59b786c0b7064fcee660aa17e373e08f9931d9/packages/vimeo-video-element/vimeo-video-element.js#L63

### PR DESCRIPTION
**Pull request by ignasio-mux**
This PR resolves #181 (and partially addressed in #159)

The previous fix updated the regex to detect event URLs but didn't modify the URL generation logic, causing events to still use the incorrect player.vimeo.com/video/ format instead of the proper vimeo.com/event/ embed URLs.

The changes modify the regex to capture the URL type (video vs event) and update the serializeIframeUrl function to generate the correct embed URLs for Vimeo events.

### CODE REVIEW

File: packages/vimeo-video-element/vimeo-video-element.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 // https://github.com/vimeo/player.js
 import VimeoPlayerAPI from '@vimeo/player/dist/player.es.js';
 const EMBED_BASE = 'https://player.vimeo.com/video';
```
Comment (ronalduQualabs) [inline packages/vimeo-video-element/vimeo-video-element.js]: This should now be named something like EMBED_VIDEO_BASE and add EMBED_EVENT_BASE

**Review by ronalduQualabs — CHANGES_REQUESTED** [review]

File: packages/vimeo-video-element/vimeo-video-element.js (hunk 1 above)
Comment (ignasio-mux) [reply packages/vimeo-video-element/vimeo-video-element.js]: done

**Review by ronalduQualabs — APPROVED** [review]
